apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.mqttServer.service.name }}
    app.kubernetes.io/instance: "{{ .Values.mqttServer.service.name }}-instance"
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/component: mqttServer
    app.kubernetes.io/managed-by: kubectl
  namespace: {{ .Values.metadata.namespace }}
  name: "{{ .Values.mqttServer.service.name }}-svc"
spec:
  selector:
    app: {{ .Values.mqttServer.name }}
  type: {{ .Values.mqttServer.service.type | default "NodePort" }}
  ports:
    {{- range .Values.mqttServer.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}